# Dependencies
#markdown:         redcarpet  # redcarpet is no longer supported!
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true  # This option has been deprecated from Jekyll

# Setup
title:            Dumb chemist energy
tagline:          'by Óscar'
description:      'A blog about Python, chemistry and data science'
url:              http://oscarigglez.github.io
baseurl:          /oscarigglez.github.io/

author:
  name:           'Oski'
  url:            https://twitter.com/oscarigglez

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/oscarigglez/oscarigglez.github.io
