# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true  # This option has been deprecated from Jekyll

# Setup
title:            Dumb chemist energy
tagline:          'A blog about Python and math'
description:      'Hey ya hey ya hey ya'
url:              http://oscarigglez.github.io
baseurl:          /

author:
  name:           'Oski'
  url:            https://twitter.com/oscarigglez

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/oscarigglez/oscarigglez.github.io
