# Dependencies
#markdown:         redcarpet  # redcarpet is no longer supported!
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true  # This option has been deprecated from Jekyll

# Setup
title:            "Óscar Igrexas"
tagline:          "jack of all trades"
description:      "Follow me on my journey through learning everything"
url:              http://oscarigglez.github.io
#baseurl:          /

author:
  name:           'oscarigrexas'
#  url:            https://twitter.com/oscarigrexas

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/oscarigglez/oscarigglez.github.io
